name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Flutter 
      uses: subosito/flutter-action@v1
    - name: Install dependencies
      run: flutter pub get
    - name:
      run: flutter pub run test
